In [ ]:
NAME            : HEMA ARULARASI.M
REGISTER NUMBER : 21UAI035
SUBJECT         : BASIC OF MACHINE LEARNING
ASSIGNMENT      : 3
DATE            : 26-12-20222

In [1]:
#Using Score Dataset

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("C:/Users/admin/OneDrive/Documents/Score_dataset.csv")
df

Experience  Test_Score  Interview_score  Salary
0           2         8.0                9   50000
1           1         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [4]:
df.Test_Score.median()

8.0

In [5]:
df.Test_Score = df.Test_Score.fillna(df.Test_Score.median())
df

Experience  Test_Score  Interview_score  Salary
0           2         8.0                9   50000
1           1         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('Salary',axis='columns'),df.Salary)

LinearRegression()

In [7]:
reg.coef_

array([3065.38179533, 1910.24754722, 2328.50109982])

In [8]:
reg.intercept_

13909.77270346706

In [9]:
reg.predict([[8,7,9]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([72761.06979505])

In [10]:
reg.predict([[7,6,10]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70113.94155232])

In [11]:
#using Home Price

In [12]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [13]:
df = pd.read_csv("C:/Users/admin/OneDrive/Documents/homeprices_bml.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
df.bedrooms.median()

4.0

In [15]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540408

In [19]:
reg.predict([[3000, 3, 40]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [20]:
reg.predict([[2500, 4, 5]])

C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])